epoch: 100
batch_size: 4
lr: 0.0001

gamma: 0.5
step_size: 50
seed: 0
dataset: psg_data
model_name: simple_net

lr_scheduler: step
lr_decay_steps: 20
lr_decay_rate: 0.5
lr_decay_min_lr: 0.00001

log_path: ./log
